### ISSUE TITLE
error running lcd.go

### ISSUE THREAD

**Issue by rabcat-zz** [hugozhu/rpi#3]
SIGILL: illegal instruction
PC=0x2490c
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall_errno(0x11b24, 0x1032dfac, 0x0)
        /home/pi/go/src/runtime/cgocall.go:130 +0x12c fp=0x1032df98 sp=0x1032df80
github.com/hugozhu/rpi._Cfunc_my_pinMode(0x0, 0x1)
        /home/pi/CSE237B/src/github.com/hugozhu/rpi/:63 +0x4c fp=0x1032dfa8 sp=0x1032df98
github.com/hugozhu/rpi.PinMode(0x0, 0x1)
        /home/pi/CSE237B/src/github.com/hugozhu/rpi/rpi.go:255 +0x2c fp=0x1032dfb4 sp=0x1032dfa8
main.main()
        /home/pi/CSE237B/src/lcd.go:11 +0x30 fp=0x1032dfc0 sp=0x1032dfb4
runtime.main()
        /home/pi/go/src/runtime/proc.go:63 +0x108 fp=0x1032dfe4 sp=0x1032dfc0
runtime.goexit()
        /home/pi/go/src/runtime/asm_arm.s:1322 +0x4 fp=0x1032dfe4 sp=0x1032dfe4

Any ideas? Thanks!

**Comment by hugozhu** [comment]
run with sudo or root?

## 

Hugo Zhu

**Comment by rabcat-zz** [comment]
Yes, as root.
